### ISSUE TITLE
https://github.com/Prana-App

### ISSUE THREAD

**Issue by serapath** [Wasl-Open-Incubator-for-NewComers/roadmap#7]

**Comment by serapath** [comment]
* stumbled upon: https://fundrazr.com/campaigns/asC86

**Comment by Oscar-Tark** [comment]
Prana is a project to bridge the gap between the homeless and resources/services such as food, housing, clothing etc. and lawyers, tax advisors, sanitary, medical, psychiatric, job seeking with no strings attached. By providing a digital platform such as a website and app.

One main aim is at getting around bureaucracy which impedes many homeless from improving their situation as they are blocked out of the system.(ex. losing your anmeldung Anmeldung). Homelessness can come in many varieties as seen in the housing shortage in Berlin where desperate residents hop from sublet to sublet with barely any money on hand or those on the roads.

Prana will also provide an analogue form of conveying information which is available in paper form and is updated every month. Information screens(through which they can see nearby resources and services or, search for what they want through the touchscreen capability) around the city and internet access points are being contemplated to allow the homeless to easily access the platform including donations of old smartphones.

Prana aims at making life for those who want to live on the street easier and give those who want to leave the street a way.
